# Generated by Django 2.2.2 on 2019-06-27 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='things',
            name='interests',
            field=models.TextField(default='default'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='things',
            name='email',
            field=models.CharField(max_length=200),
        ),
    ]
