# Generated by Django 3.1.1 on 2020-09-02 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0002_auto_20190627_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='things',
            name='interests',
            field=models.TextField(default='N/A'),
        ),
    ]
